language: android
script:
  - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - export TERM=dumb
  - echo sdk.dir $ANDROID_HOME > local.properties
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository

