language: android
sudo: false
script:
  - jdk_switcher use oraclejdk8
  - echo sdk.dir $ANDROID_HOME > local.properties
  - export TERM=dumb
  - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
  - ./gradlew --stacktrace assemble
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
before_install:
 - yes | sdkmanager "platforms;android-27"
